### PR TITLE
Use Homebrew as upstream for new installs

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Woohoo! 🎉

We need to address one small issue, `HOMEBREW_CACHE` and `HOMEBREW_LOGS` aren't yet set appropriately on Linux. @jonchang had said he'd like to take a crack at this issue.

I suggest we hold off until after the holiday break (after new year).

**Comment by jonchang** [comment]
https://github.com/Homebrew/brew/pull/5446
https://github.com/Homebrew/brew/pull/5447

Still need to add checks for development tools on Linux but I think this will help a lot.

**Comment by sjackman** [comment]
Excellent! Thanks, Jon!

**Review by sjackman — APPROVED** [review]
🥂

**Comment by jonchang** [comment]
🎉

**Comment by sjackman** [comment]
🎆 🥂

**Comment by maxim-belkin** [comment]
:this-is-fine: :) 🍾

**Pull request merged**
