### PR TITLE
Change default installation path to /usr/local

### PR DESCRIPTION
**Pull request by cjmao**

### CODE REVIEW

**Comment by cjmao** [comment]
Sorry, a mistake. I've closed this pr.

**Comment by sjackman** [comment]
No worries. Have you successfully been using Linuxbrew installed in `/usr/local`, and on which distribution of Linux?

**Comment by cjmao** [comment]
At least it looks like working for me.
I'm using Ubuntu 16.04.

I made this modification because I had an issue when I was trying to deploy a rails app using capistrano.
I installed bundler using brewed gem and found that cap (more specifically, sshkit) cannot find bundler on deployment machine. I tried to configure PATH but it still doesn't work.
So I think maybe installing brew to /usr/local which is in default PATH will do.

**Comment by sjackman** [comment]
Cool. This can possibly go badly if you install a library in `/usr/local/lib` that has the same file name as a library in `/usr/lib`. If the two libraries are incompatible, it could break some of your software installed in `/usr/bin`. If it's working for you though, great. We build the Linuxbrew binary packages on Ubuntu 16.04 Xenial, so there's a good chance that it will work for you. It may not work so well on other distributions of Linux.

**Comment by cjmao** [comment]
Thx for the tip. :)

**Pull request closed without merging**
